# Generated by Django 3.0.7 on 2020-06-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meto_admin_app', '0003_auto_20200614_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='worker_id',
            new_name='id',
        ),
    ]
