# Generated by Django 3.0.7 on 2020-06-15 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meto_user_app', '0004_delete_dates'),
        ('meto_admin_app', '0003_auto_20200615_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('staff_assigned_date', models.DateField()),
                ('technician_assigned_date', models.DateField()),
                ('technician_visited_date', models.DateField()),
                ('close_date', models.DateField()),
                ('booking_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meto_user_app.booking')),
            ],
        ),
    ]
