# Generated by Django 3.0.7 on 2020-06-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meto_admin_app', '0004_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
