# Generated by Django 3.0.7 on 2020-06-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meto_admin_app', '0007_auto_20200620_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='staff_assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='technician_assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='technician_visited_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='visiting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
