# Generated by Django 3.0.7 on 2020-06-14 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meto_admin_app', '0001_initial'),
        ('meto_user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='meto_user_app.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='staff_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='meto_admin_app.staff'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='meto_user_app.user'),
        ),
        migrations.AddField(
            model_name='booking',
            name='worker_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='meto_admin_app.worker'),
        ),
        migrations.AddField(
            model_name='dates',
            name='booking_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meto_user_app.booking'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
