# Generated by Django 3.0.7 on 2020-06-15 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meto_user_app', '0002_auto_20200614_2218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assign',
        ),
    ]
