# Generated by Django 3.0.7 on 2020-06-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meto_user_app', '0003_delete_assign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dates',
        ),
    ]
