# Generated by Django 3.0.7 on 2020-06-19 07:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meto_user_app', '0004_delete_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='recovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=255, unique=True)),
                ('recovery_id', models.CharField(max_length=255)),
                ('recovery_time', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_dp',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('booking_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meto_user_app.booking')),
            ],
        ),
    ]
